[window]
dimensions                = { columns = 85, lines = 25 }
position                  = { x = 100, y = 100 }
padding                   = { x = 20, y = 20 }
dynamic_padding           = true
decorations               = "Full"
startup_mode              = "Windowed"
title                     = "Terminal"
dynamic_title             = false
decorations_theme_variant = "Dark"

[scrolling]
history    = 10000
multiplier = 2

[font]
normal      = { family = "GeistMono Nerd Font Mono", style = "Regular" }
bold        = { family = "GeistMono Nerd Font Mono", style = "Bold" }
italic      = { family = "GeistMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "GeistMono Nerd Font Mono", style = "Bold Italic" }
size        = 16
offset      = { x = 0, y = 0 }

[colors.primary]
background = '#101010'
foreground = '#FFFFFF'

[colors.cursor]
text   = '#101010'
cursor = '#FFC799'

[colors.selection]
text       = 'CellForeground'
background = '#505050'

[colors.normal]
black   = '#101010'
red     = '#FF8080'
green   = '#99FFE4'
yellow  = '#FFC799'
blue    = '#A0A0A0'
magenta = '#FF7300'
cyan    = '#99FFE4'
white   = '#FFFFFF'

[colors.bright]
black   = '#505050'
red     = '#FF8080'
green   = '#99FFE4'
yellow  = '#FFCFA8'
blue    = '#A0A0A0'
magenta = '#FF8080'
cyan    = '#99FFE4'
white   = '#FFFFFF'

[selection]
save_to_clipboard = true

[cursor]
style            = { shape = "block", blinking = "On" }
vi_mode_style    = { shape = "block", blinking = "On" }
blink_interval   = 500
blink_timeout    = 0
unfocused_hollow = false

[terminal]
shell = { program = "C:\\Program Files\\Git\\bin\\bash.exe", args = ["--login"] }
osc52 = "OnlyCopy"

[mouse]
hide_when_typing = true
