[window]
dimensions                = { columns = 60, lines = 20 }
position                  = { x = 100, y = 100 }
padding                   = { x = 35, y = 5 }
dynamic_padding           = true
decorations               = "Full"
startup_mode              = "Windowed"
title                     = "Terminal"
dynamic_title             = false
decorations_theme_variant = "Dark"

[scrolling]
history    = 10000
multiplier = 2

[font]
normal      = { family = "GeistMono NFM", style = "Regular" }
bold        = { family = "GeistMono NFM", style = "Bold" }
italic      = { family = "GeistMono NFM", style = "Italic" }
bold_italic = { family = "GeistMono NFM", style = "Bold Italic" }
size        = 14
offset      = { x = 0, y = 0 }

[colors.primary]
background = '#0f1017'
foreground = '#a6accd'

[colors.normal]
black   = '#0f1017'
red     = '#d0679d'
green   = '#5DE4c7'
yellow  = '#fffac2'
blue    = '#89ddff'
magenta = '#f087bd'
cyan    = '#89ddff'
white   = '#ffffff'

[colors.bright]
black   = '#a6accd'
red     = '#d0679d'
green   = '#5DE4c7'
yellow  = '#fffac2'
blue    = '#ADD7FF'
magenta = '#f087bd'
cyan    = '#ADD7FF'
white   = '#ffffff'

[colors.cursor]
text   = '#0f1017'
cursor = '#a6accd'

[colors.selection]
text       = '#0f1017'
background = '#717cb4'

[selection]
save_to_clipboard = true

[cursor]
style            = { shape = "Underline", blinking = "On" }
vi_mode_style    = { shape = "Underline", blinking = "On" }
blink_interval   = 500
blink_timeout    = 0
unfocused_hollow = false

[terminal]
shell = { program = "C:\\Program Files\\Git\\bin\\bash.exe", args = ["--login"] }
osc52 = "OnlyCopy"

[mouse]
hide_when_typing = true
