[window]
dimensions                = { columns = 85, lines = 25 }
position                  = { x = 100, y = 100 }
dynamic_padding           = true
decorations               = "Full"
startup_mode              = "Maximized"
title                     = "Terminal"
dynamic_title             = false
decorations_theme_variant = "Dark"

[scrolling]
history    = 10000
multiplier = 2

[font]
normal      = { family = "GeistMono Nerd Font Mono", style = "Regular" }
bold        = { family = "GeistMono Nerd Font Mono", style = "Bold" }
italic      = { family = "GeistMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "GeistMono Nerd Font Mono", style = "Bold Italic" }
size        = 14
offset      = { x = 0, y = 0 }

[colors.primary]
background = '#000000'
foreground = '#c1c1c1'

[colors.cursor]
cursor = '#c1c1c1'
text   = '#000000'

[colors.normal]
black   = '#3E2018'
red     = '#5f8787'
green   = '#c1c1c1'
yellow  = '#888888'
blue    = '#aaaaaa'
magenta = '#999999'
cyan    = '#fbcb97'
white   = '#c1c1c1'

[colors.bright]
black   = '#505050'
red     = '#5f8787'
green   = '#c1c1c1'
yellow  = '#888888'
blue    = '#aaaaaa'
magenta = '#e78a43'
cyan    = '#fbcb97'
white   = '#c1c1c1'

[[colors.indexed_colors]]
index = 16
color = '#aaaaaa'

[[colors.indexed_colors]]
index = 17
color = '#5f8787'

[cursor]
style            = { shape = "block", blinking = "On" }
vi_mode_style    = { shape = "block", blinking = "On" }
blink_interval   = 500
blink_timeout    = 0
unfocused_hollow = false

[selection]
save_to_clipboard = true

[terminal]
shell = { program = "/bin/bash", args = ["--login"] }
osc52 = "OnlyCopy"

[mouse]
hide_when_typing = true
#dd9999
