[window]
dimensions                = { columns = 80, lines = 25 }
position                  = { x = 100, y = 100 }
padding                   = { x = 30, y = 30 }
dynamic_padding           = true
decorations               = "Full"
startup_mode              = "Windowed"
title                     = "Terminal"
dynamic_title             = false
decorations_theme_variant = "Dark"

[scrolling]
history    = 10000
multiplier = 2

[font]
normal      = { family = "GeistMono NFM", style = "Regular" }
bold        = { family = "GeistMono NFM", style = "Bold" }
italic      = { family = "GeistMono NFM", style = "Italic" }
bold_italic = { family = "GeistMono NFM", style = "Bold Italic" }
size        = 14
offset      = { x = 0, y = 0 }

[colors.primary]
background = '#151515'
foreground = '#c3c9c2'

[colors.normal]
black   = '#151515'
red     = '#78535D'
green   = '#737a6f'
yellow  = '#a59e8a'
blue    = '#807c82'
magenta = '#e0c6cd'
cyan    = '#6A5E5E'
white   = '#c3c9c2'

[colors.bright]
black   = '#4a4a4a'
red     = '#78535D'
green   = '#737a6f'
yellow  = '#a59e8a'
blue    = '#807c82'
magenta = '#e0c6cd'
cyan    = '#6A5E5E'
white   = '#e7e7e7'

[colors.cursor]
text   = '#151515'
cursor = '#c3c9c2'

[colors.selection]
text       = '#e7e7e7'
background = '#252525'

[selection]
save_to_clipboard = true

[cursor]
style            = { shape = "Underline", blinking = "On" }
vi_mode_style    = { shape = "Underline", blinking = "On" }
blink_interval   = 500
blink_timeout    = 0
unfocused_hollow = false

[terminal]
shell = { program = "C:\\Program Files\\Git\\bin\\bash.exe", args = ["--login"] }
osc52 = "OnlyCopy"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "M",    mods = "Alt", action = "ToggleMaximized" },
  { key = "W",    mods = "Alt", action = "Minimize" },
  { key = "Q",    mods = "Alt", action = "Quit" },
  { key = "Up",   mods = "Alt", action = "ScrollLineUp" },
  { key = "Down", mods = "Alt", action = "ScrollLineDown" }
]
