[window]
dimensions                = { columns = 85, lines = 25 }
position                  = { x = 100, y = 100 }
dynamic_padding           = true
decorations               = "Full"
startup_mode              = "Windowed"
title                     = "Terminal"
dynamic_title             = false
decorations_theme_variant = "Dark"

[scrolling]
history    = 10000
multiplier = 2

[font]
normal      = { family = "GeistMono NFM", style = "Regular" }
bold        = { family = "GeistMono NFM", style = "Bold" }
italic      = { family = "GeistMono NFM", style = "Italic" }
bold_italic = { family = "GeistMono NFM", style = "Bold Italic" }
size        = 16
offset      = { x = 0, y = 0 }

[colors.primary]
background = '#181818'
foreground = '#e4e4e4'

[colors.cursor]
text   = '#181818'
cursor = '#88c0d0'

[colors.selection]
text       = '#e4e4e4'
background = '#262626'

[colors.normal]
black   = '#141414'
red     = '#e34671'
green   = '#3fa266'
yellow  = '#f1b467'
blue    = '#81a1c1'
magenta = '#AAA0FA'
cyan    = '#88c0d0'
white   = '#e4e4e4'

[colors.bright]
black   = '#262626'
red     = '#fc6b83'
green   = '#70b489'
yellow  = '#d2943e'
blue    = '#87C3FF'
magenta = '#E394DC'
cyan    = '#82D2CE'
white   = '#fcfcfc'

[selection]
save_to_clipboard = true

[cursor]
style            = { shape = "Underline", blinking = "On" }
vi_mode_style    = { shape = "Underline", blinking = "On" }
blink_interval   = 500
blink_timeout    = 0
unfocused_hollow = false

[terminal]
shell = { program = "C:\\Program Files\\Git\\bin\\bash.exe", args = ["--login"] }
osc52 = "OnlyCopy"

[mouse]
hide_when_typing = true
