[window]
dimensions                = { columns = 85, lines = 25 }
position                  = { x = 100, y = 100 }
dynamic_padding           = true
decorations               = "Full"
startup_mode              = "Windowed"
title                     = "Terminal"
dynamic_title             = true
decorations_theme_variant = "Dark"

[scrolling]
history    = 10000
multiplier = 2

[font]
normal      = { family = "GeistMono Nerd Font Mono", style = "Regular" }
bold        = { family = "GeistMono Nerd Font Mono", style = "Bold" }
italic      = { family = "GeistMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "GeistMono Nerd Font Mono", style = "Medium Italic" }
size        = 14
offset      = { x = 0, y = 0 }

[colors.primary]
background = '#000000'
foreground = '#c1c1c1'

[colors.cursor]
cursor = '#c1c1c1'
text   = '#000000'

[colors.normal]
black   = '#000000'
red     = '#dd9999'
green   = '#5f8787'
yellow  = '#a06666'
blue    = '#888888'
magenta = '#999999'
cyan    = '#aaaaaa'
white   = '#c1c1c1'

[colors.bright]
black   = '#333333'
red     = '#dd9999'
green   = '#5f8787'
yellow  = '#a06666'
blue    = '#888888'
magenta = '#999999'
cyan    = '#aaaaaa'
white   = '#c1c1c1'

[cursor]
style            = { shape = "beam", blinking = "Off" }
blink_interval   = 500
blink_timeout    = 0
unfocused_hollow = false

[selection]
save_to_clipboard = true
