[window]
dimensions                = { columns = 85, lines = 25 }
position                  = { x = 100, y = 100 }
dynamic_padding           = true
decorations               = "None"
startup_mode              = "Maximized"
title                     = "Terminal"
dynamic_title             = false
decorations_theme_variant = "Dark"

[scrolling]
history    = 10000
multiplier = 2

[font]
normal      = { family = "GeistMono Nerd Font Mono", style = "Regular" }
bold        = { family = "GeistMono Nerd Font Mono", style = "Medium" }
italic      = { family = "GeistMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "GeistMono Nerd Font Mono", style = "Medium Italic" }
size        = 12
offset      = { x = 0, y = 0 }

[colors.primary]
background = '#000000'
foreground = '#c1c1c1'

[colors.cursor]
cursor = '#c1c1c1'
text   = '#000000'

[colors.normal]
black   = '#000000'
red     = '#5f8787'
green   = '#fbcb97'
yellow  = '#e78a53'
blue    = '#888888'
magenta = '#999999'
cyan    = '#aaaaaa'
white   = '#c1c1c1'

[colors.bright]
black   = '#333333'
red     = '#5f8787'
green   = '#fbcb97'
yellow  = '#e78a53'
blue    = '#888888'
magenta = '#999999'
cyan    = '#aaaaaa'
white   = '#c1c1c1'

[cursor]
style            = { shape = "block", blinking = "Off" }
blink_interval   = 500
blink_timeout    = 0
unfocused_hollow = false

[selection]
save_to_clipboard = true

[terminal]
shell = { program = "/bin/bash", args = ["--login"] }
osc52 = "OnlyCopy"

[mouse]
hide_when_typing = true
