"$schema" = "https://starship.rs/config-schema.json"

format = """
$directory\
$git_branch\
$character\
"""

[username]
show_always = true
style_user = "white bold"
style_root = "white bold"
format = "[$user ]($style)"

[character]
success_symbol = "[➜](bold white)"
error_symbol = "[➜](bold red)"
vimcmd_symbol = "[➜](bold yellow)"

[directory]
format = "[$path]($style) "
style = "#5f8787"
truncation_length = 1
truncation_symbol = ""

[git_branch]
symbol = ""
format = "[($symbol $branch)]($style) "
style = "#dd9999"
