"$schema" = "https://starship.rs/config-schema.json"

add_newline = true

palette = "noir_poimandres"

format = "$directory$git_branch$git_status$golang$nodejs$python$character"

[palettes.noir_poimandres]
base           = "#0f1017"
surface        = "#303340"
overlay        = "#202430"
muted          = "#767c9d"
subtle         = "#303340"
text           = "#a6accd"
error          = "#d0679d"
success        = "#5DE4c7"
warning        = "#fffac2"
blue           = "#ADD7FF"
magenta        = "#f087bd"
cyan           = "#89ddff"
highlight_low  = "#ADD7FF20"
highlight_med  = "#ADD7FF40"
highlight_high = "#ADD7FF40"

[character]
success_symbol = "[❯](bold fg:success)"
error_symbol   = "[❯](bold fg:error)"
vimcmd_symbol  = "[❯](bold fg:blue)"

[directory]
format            = "[$path ](bold fg:cyan)"
truncation_length = 1
truncation_symbol = ""

[git_branch]
symbol = ""
format = "[$symbol $branch](bold fg:blue) "

[git_status]
disabled = true
